FROM php:8.3-apache

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libonig-dev \
    zip \
    unzip \
    git \
    curl \
    libxml2-dev \
    libzip-dev \
    libssl-dev \
    libpq-dev \
    && docker-php-ext-install pdo_pgsql pdo_mysql mbstring exif pcntl bcmath gd xml

# Instalar Composer desde imagen oficial
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Establecer directorio de trabajo
WORKDIR /var/www/html

# Agregar como directorio seguro para Git
RUN git config --global --add safe.directory /var/www/html

# Copiar todos los archivos del proyecto
COPY . .

# Limpiar el directorio vendor y cache de Composer
RUN rm -rf vendor composer.lock && composer clear-cache

# Instalar dependencias de Laravel
RUN composer install --optimize-autoloader
# RUN composer install --no-dev --optimize-autoloader

# Esto se usa cuando haya almacenamiento interno en el proyecto
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Asignar permisos correctos a los directorios necesarios por Laravel
RUN chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

# Exponer puerto 80
EXPOSE 80

# Copiar configuración de Apache y habilitar mod_rewrite
COPY default.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite

# Crear symlink de storage
RUN php artisan storage:link

# Instalar extensión Redis
RUN pecl install redis && docker-php-ext-enable redis

# Iniciar cola de trabajo
# CMD php artisan queue:work --queue=auth
